### ISSUE TITLE
Change the Google Service Name from "WMail-fork" to "openWMail"

### ISSUE THREAD

**Issue by jadenPete** [openWMail/openWMail#14]
What the title says.

**Comment by geekgonecrazy** [comment]
@jadenPete which screen are you seeing that naming?

**Comment by jadenPete** [comment]
![screen](https://cloud.githubusercontent.com/assets/13180372/25731000/faf9f636-30f6-11e7-97c4-b8f7a574a890.png)
![screen2](https://cloud.githubusercontent.com/assets/13180372/25731001/fb0ae3d8-30f6-11e7-9341-d61aa5ea6a52.png)

**Comment by WillPresley** [comment]
@jadenPete @geekgonecrazy I've just added fresh Linux and macOS builds to the initial release, the Windows builds were fine, I just forgot to update credentials on my Macbook. Please let me know if those builds are showing the proper name/using the proper oAuth 2.0 creds!

**Comment by jadenPete** [comment]
@WillPresley I downloaded a fresh Linux build and installed it, the proper name is not showing.

**Comment by WillPresley** [comment]
@jadenPete Any chance you could hop into Rocket Chat at some point? https://openwmail.rocket.chat/channel/general

I'm curious if it is because I used the same filename, let's try something different. Snag a *_fix build and let me know!

https://github.com/openWMail/openWMail/releases/tag/v1.0.0

**Comment by WillPresley** [comment]
We confirmed with some internal testing on the *_fix builds I uploaded that the oAuth name is now correct. Thanks for the report, I definitely messed that up the first time!

**Comment by jadenPete** [comment]
I also remember that I didn't restart WMail so the old one was still in memory
