### ISSUE TITLE
Arch install issues

### ISSUE THREAD

**Issue by geekgonecrazy** [openWMail/openWMail#15]
* Which version of openWMail are you using? 1.0.0

* Which Operating System are you using? Manjaro

Transplanted from off-topic in #13 

cc: @SMed79 @jadenPete

Conversation from ticket:
<details>

#### SMed79 - May 5th, 2017 8:36 CDT
Manjaro GNOME Edition 17.0.1 / 64-bit

```
sudo dpkg -i openWMail_1-0-0_Linux_x64.deb

dpkg: dependency problems prevent configuration of openwmail:
 openwmail depends on lsb-base (>= 3.2); however:
The lsb-base package is not installed.

openwmail depends on libappindicator1 (> = 12.10.1); however:
The libappindicator1 package is not installed.

dpkg: packet processing error openwmail (--install):
 dependency problems - leaving unconfigured
errors were encountered during execution
openwmail
```

#### jadenPete - May 5th, 2017 9:28 CDT
Two things. Manjaro uses DPKG? And you must install lsb-base and libappindicator.

#### SMed79 - May 5th, 2017 10:37 CDT
> Manjaro uses DPKG?

dpkg installed form [AUR](https://aur.archlinux.org/packages/dpkg/) to manage debian package.

> you must install lsb-base and libappindicator

libappindicator is already installed and concerning `lsb-base` 
pacman/yaourt ==> `error: target not found: lsb-base`

#### geekgonecrazy - May 5th, 2017 12:24 CDT
@SMed79 give this a try: https://aur.archlinux.org/packages/openwmail/ I for sure wouldn't recommend relying on dpkg on arch. :)

#### SMed79 - May 5th, 2017 15:34 CDT
That better, it's correctly installed :) THANK YOU.

...& FYI, after the intallation the chmod was  **rw-r--r--**

`$ stat --format=%a /opt/openwmail/openWMail` ==> `644`
</details>

**Comment by geekgonecrazy** [comment]
@SMed79 I pushed a revision setting chmod +x let me know if you have any more issues here on arch

**Comment by SMed79** [comment]
Err_1

> The requested URL returned error: 404 Not Found

PKGBUILD ==> `source_x86_64=` (**_fix**).

Err_2

> chmod: cannot access `/opt/openwmail/openWMail' : No such file or directory
> ERROR: An error occurred in package ().
> Abandon...
> ERROR : Makepkg Could not build openwmail.

Did we try to apply the chmod before the installation?

**Comment by geekgonecrazy** [comment]
Fixed the download error.  :smile: but... it does appear despite having the execute bit... its losing it.

If you're familiar with the AUR.  maybe you have ideas?

```
pkgname=openwmail
pkgver=1.0.0
pkgverdash=1-0-0
pkgrel=2
pkgdesc="openwmail"
arch=('x86_64')
license=('MLP-2.0')
url="https://github.com/openwmail/openwmail"
options=()

source_x86_64=("https://github.com/openWMail/openWMail/releases/download/v${pkgver}/openWMail_${pkgverdash}_Linux_x86_64.deb")
md5sums_x86_64=('d84ceea682905b58531c43f5962317fb')

depends=('libnotify' 'gconf')
optdepends=()

package() {
        cd "${srcdir}"

        tar xf data.tar.gz -C "${pkgdir}"

        chmod 755 $pkgdir/opt
        chmod 755 $pkgdir/usr
        chmod 755 $pkgdir/usr/share
        chmod 755 $pkgdir/usr/share/applications

        mkdir -p "$pkgdir/usr/bin"
	chmod +x /opt/openwmail/openWMail

        ln -s /opt/openwmail/openWMail ${pkgdir}/usr/bin
}
```

During the package process I verified it definitely is set right:
```
-rwxr-xr-x 1 root root 80394960 May  6 19:57 /opt/openwmail/openWMail
```

But at install... it seems to copy over differently
```
[root@arch0505 openwmail]# ls -l /opt/openwmail/openWMail 
-rw-r--r-- 1 root root 80394960 May  6 20:03 /opt/openwmail/openWMail
```

**Comment by FabioLolix** [comment]
Hi, seen this issue on Manjaro forum,

Edit to:

> chmod +x $pkgdir/opt/openwmail/openWMail

**Comment by SMed79** [comment]
> seen this issue on Manjaro forum

https://forum.manjaro.org/t/openwmail-pkgbuild-wrong-chmod-of-the-binary/23248/2

> Edit to:  chmod +x $pkgdir/opt/openwmail/openWMail

Fixed, thank you for you time.

**Comment by geekgonecrazy** [comment]
@FabioLolix hey thanks for jumping over here and commenting!  I've updated the PKGBUILD.  Makes sense that needs to be pointing to the file relative to the package directory and not its final install location.  :+1:

**Comment by geekgonecrazy** [comment]
i'll go ahead and close this out.  Let me know if you have any other arch issues :+1:

**Comment by FabioLolix** [comment]
Good. Some "PKGBUILD etiquette" improvements can be made, I'll take a look in the next days

**Comment by MggMuggins** [comment]
Shouldn't this be put on the Readme/Website/Both? I would have liked to have known that there was an AUR package available.

**Comment by geekgonecrazy** [comment]
@MggMuggins absolutely! I'll add to readme

**Comment by geekgonecrazy** [comment]
PR opened #34

**Comment by FabioLolix** [comment]
@geekgonecrazy would you like to add me as pkgbuild co-maintainer on the AUR?
My account is FabioLolix there
