### ISSUE TITLE
Collaborating pt. 2

### ISSUE THREAD

**Issue by WillPresley** [openWMail/openWMail#2]
I'm fairly stupid and deleted my old repo instead of just redirecting to this one, so we can re-gather our thoughts here instead.

@jadenPete, you interested in this at all?

**Comment by geekgonecrazy** [comment]
:grin: all good.  This works :+1:

**Comment by WillPresley** [comment]
@geekgonecrazy Any chance you could toss write access to the repo my way? I don't have anything major to add yet, but wanted to update the Readme a little bit, and be ready to build and upload releases once the name and versioning stuff has been fixed through the repo.

**Comment by geekgonecrazy** [comment]
@WillPresley done!  Sorry about that.  Thought adding to the org and then importing would have taken care of that.

**Comment by jadenPete** [comment]
Yes, I am! Sad to see WMail get tossed. I don't know much Electron programming, but I can help with other stuff.

**Comment by WillPresley** [comment]
@jadenPete I'm also learning the Electron side of things from scratch, but the vast majority of the codebase is actually Javascript, which is just fine to me. Glad to hear it! Later today I may toss a quick Slack team together for us for this or something, thoughts?

**Comment by SMed79** [comment]
> deleted my old repo instead of just redirecting to this one

Cloned before get deleted https://github.com/SMed79/wmail-fork

**Comment by geekgonecrazy** [comment]
> Slack team together for us for this or something, thoughts?

I'm actually one of the core devs on the open source Rocket.Chat.  I can spin us up a server with no message limits or anything of that sort.  I try and dogfood as much as possible :)

Just let me know it'll take me like a second to start one :)

**Comment by WillPresley** [comment]
Very cool, let's use that for sure then!

Random question, has anyone had any luck building the Windows MSI installers from the command line (on any platform)? I can't make it work on Windows or macOS, but was easily able to use the *.aip files along with Advanced Installer to create them. Obviously I intend on opening a proper issue for that once I narrow down the error(s).

**Comment by jadenPete** [comment]
I'm using Debian so I wouldn't know. A Slack team sounds perfect though.

**Comment by geekgonecrazy** [comment]
@jadenPete we've got a Rocket.Chat server setup at: https://openwmail.rocket.chat - similar to Slack but open source with a team that are also fans of open source as well :)

**Comment by geekgonecrazy** [comment]
Now that we've gotten an initial version cut going to go ahead and close this.  Feel free to join us in the rocket.chat channel! We'd love to have you.
