### ISSUE TITLE
Feature Request: Custom services

### ISSUE THREAD

**Issue by nsrosenqvist** [openWMail/openWMail#20]
Is there any interest in implementing custom or additional service support? For example to add your own instance of Nextcloud, or other services such as Trello, Slack, or any intranet site you might be using daily in your work.

**Comment by geekgonecrazy** [comment]
Related to #17 the current feeling is no.  But maybe very, generic wrappers if people really want this

**Comment by nsrosenqvist** [comment]
Must have missed #17 so I guess we can close this issue.
