### ISSUE TITLE
Rename & versioning

### ISSUE THREAD

**Issue by geekgonecrazy** [openWMail/openWMail#3]
How far should we take a rename of this fork?  

Is this name ok or should it be different?  I just wanted to get the ball rolling.

Also versioning.  I'm inclined to start at 1.0.0 and increase as we go. But not apposed to keeping the versions wmail had

**Comment by WillPresley** [comment]
I think openWMail works for the name, at least until we start doing meaningful changes to the codebase.

As for versioning, I am fine with the idea of starting at 1.0.0, and that gives us the ability to sub-version however we please.

**Comment by WillPresley** [comment]
#4 Is this as well.
