### ISSUE TITLE
Linux compiled tarballs

### ISSUE THREAD

**Issue by aetha** [openWMail/openWMail#30]
Just wondering if some easy pre-compiled + packaged as .tar.* releases could be added. (I prefer .tar.xz but .tar.gz is fine.)

I can see these used to be available before Thomas101 took 'em down, looking at these wmail-bin ebuilds for Gentoo: https://gpo.zugaina.org/mail-client/wmail-bin

**Comment by ronenrozner** [comment]
Download the .deb package, and expand. expand the data.tar.gz file. inside you will find the openWmail folder which you can either run the app from, or copy to your bin folder like all other apps. that should get you going.

**Comment by geekgonecrazy** [comment]
I think it wouldn't take much effort to do this.  

For the arch AUR we're doing as @ronenrozner mentions above.  But I can see it'd be nice to be able to drop new links in and continue off.  

I'll take a look at adding that

**Comment by geekgonecrazy** [comment]
@aetha added!  https://github.com/openWMail/openWMail/releases/tag/v1.0.0
