### ISSUE TITLE
What is missing to display unread counter in tray icon (Linux, KDE) ?

### ISSUE THREAD

**Issue by ronenrozner** [openWMail/openWMail#31]
* Which version of openWMail are you using? [1.0]

* Which Operating System are you using? [openSuse Leap 42.3, KDE, 64 bit]

Does anybody remember what do I need to install in order to display the tray icon badge with the unread count ?

**Comment by geekgonecrazy** [comment]
Nothing extra is needed to view unread count generally.. I haven't tried it at all on KDE though.  I would figure it would work the same.

**Comment by ronenrozner** [comment]
Thanks for the comment. I remember with the original Wmail, there was a thread about it. Some library needed in order to display the icon on the task manager. right now all i have is a black square.

**Comment by geekgonecrazy** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1057 might actually be related to this?  I see several cases like this across electron projects.  Seems something to do with KDE wanting a 32x32 image

**Comment by ronenrozner** [comment]
SOLVED ! 
libappindicator1 was missing.

**Comment by geekgonecrazy** [comment]
@ronenrozner perfect!  Glad you got it!

**Comment by geekgonecrazy** [comment]
@ronenrozner perfect!  Glad you got it!
