### ISSUE TITLE
Other providers mail accounts?

### ISSUE THREAD

**Issue by jmicgz** [openWMail/openWMail#39]
* Which version of openWMail are you using? [e.g. 1.3.1]
1.3.1
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

I have an yahoo and outlook accounts that i want to use on the same app no need for many integration since are secondary accounts maybe the inclusion of add a custom url? I know i can use rambox for that but i love wmail

**Comment by SMed79** [comment]
Related to https://github.com/openWMail/openWMail/issues/17

**Gmail Help**:
* Check emails from other accounts https://support.google.com/mail/answer/21289
* Send emails from a different address https://support.google.com/mail/answer/22370
* https://webapps.stackexchange.com/questions/76562/#82299

**Comment by geekgonecrazy** [comment]
Going to go ahead and close as beyond the scope of the intentions here.
