### ISSUE TITLE
G suite (formerly Google Apps) account does not stay signed in

### ISSUE THREAD

**Issue by ksurl** [openWMail/openWMail#41]
* Which version of openWMail are you using? [e.g. 1.3.1]
1.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

my school email keeps asking me to sign in. It stays signed in Chrome when I tested so it's not on the admin end. my main gmail account works and stays signed in. are there any logs or debug I can attach to help check this?

**Comment by ksurl** [comment]
I just found the artificial cookies setting. after restarting the client, it still asks for sign in.

**Comment by MggMuggins** [comment]
Does your school account do the same thing in a normal web browser (specifically, not chrome)?

**Comment by ksurl** [comment]
tried it in edge and it does do that. I guess it's on their end. thanks
