### ISSUE TITLE
Authentication disable

### ISSUE THREAD

**Issue by nkkollaw** [openWMail/openWMail#67]
Hi!

I'm using openWMail 1.0 on macOS Mojave, and it looks as if Google has disabled authentication for the app. I'm unable to login and add new accounts.

Is there any solution to this? I think whoever has access to the developer account should update permissions.

**Comment by zetrotrack000** [comment]
I am having similar issue. OpenWMail is giving message to re-authenticate account. Upon clicking "Re-Authenticate Account", Google  is giving message that "Sign in with Google temporarily disabled for this app". Kindly help to solve this issue. Thanks

**Comment by nkkollaw** [comment]
The owner of the Google app must solve this. We cannot do anything besides changing the app ID running from source code.

**Comment by zetrotrack000** [comment]
OpenWMail is a fork of WMail, which is now called WaveBox. I have installed it, looks good with far more features.

**Comment by nkkollaw** [comment]
WTF are you talking about, @zetrotrack000?

**Comment by c-m-a-n** [comment]
There is on-going dialogue on this issue:

https://github.com/openWMail/openWMail/issues/63

The author/developer @geekgonecrazy has commented there, though I'm not sure what the next actions are. 

No idea why @zetrotrack000 is referring to WaveBox, its the resulting product once the original OpenMail developer sold his codebase. The free version supports just 2 accounts, any more and you have to pay (to use a Gmail wrapper client? can't see too many paying customers for that).

**Comment by nkkollaw** [comment]
> No idea why @zetrotrack000 is referring to WaveBox, its the resulting product once the original OpenMail developer sold his codebase. 

The comment is so out of context that it looks like a bot. Anyway, WaveBox completely sucks, so I agree with you.

**Comment by geekgonecrazy** [comment]
Closing in favor of #63

**Comment by WillPresley** [comment]
> No idea why @zetrotrack000 is referring to WaveBox, its the resulting product **once the original OpenMail developer sold his codebase**. The free version supports just 2 accounts, any more and you have to pay (to use a Gmail wrapper client? can't see too many paying customers for that).

As we are about 99% standing on the back of his work, I felt the need to correct some of the above relating to Wavebox and Thomas (the author of Wmail and Wavebox). 

The codebase was not sold (at least as far as anyone knows publicly). Thomas spun his open-source project into a company and service. He is still the primary developer and very actively engaged with the community. It is true that there is a limit of two _Google accounts_ for the free tier, but in all fairness, Wavebox is much, MUCH more than just a 'Gmail wrapper client'. I am trying it out, and currently have:
- Personal Gmail on left, along with ProtonMail, Google Calendar, Google Keep, Google Drive, Google Contacts, Google Analytics, and Google Photos
- Professional Gmail on left, along with Drive and Analytics
- Work Gmail on left, along with Google Calendar, Google Contacts, Bitbucket, and Trello
It's a pretty great setup, and not anything openWmail can (or would) ever be able to do. I, of course, miss my slightly faster, less memory-intensive openWmail setup, so I'm hoping that #63 has some positive results, but Wavebox (and Rambox, if you're counting) are great at what they do as well, which is to wrap sites and services in logical, customizable chunks and keep them outside of the main browser.

**Comment by c-m-a-n** [comment]
> As we are about 99% standing on the back of his work, I felt the need to correct some of the above relating to Wavebox and Thomas (the author of Wmail and Wavebox).
Thanks for clarifying, appreciated. On reflection perhaps my comments were too direct and assumptive. Cheers.

**Comment by geekgonecrazy** [comment]
> I felt the need to correct some of the above relating to Wavebox and Thomas (the author of Wmail and Wavebox).

Thanks for adding that clarification here!  I totally skimmed over that portion.
