### ISSUE TITLE
can not authenticate when adding mail

### ISSUE THREAD

**Issue by formanvolovec** [openWMail/openWMail#72]
version [1.0.0]
[Linux Mint 19.3]

![Снимок экрана в 2019-12-31 02-47-22](https://user-images.githubusercontent.com/46429464/71605522-778daf00-2b7a-11ea-980e-28a1ee5091ce.png)

what can i do?

**Comment by geekgonecrazy** [comment]
#63 :( unfortunately Google kinda nuked us.  I haven't had bandwidth to work past it.  If someone else is interested in helping definitely jump in
