### ISSUE TITLE
"Browser or app not secure" error msg - cant add gmail accounts to WMail

### ISSUE THREAD

**Issue by jwnyc1** [openWMail/openWMail#73]
LINUX NEWBIE!! Using Wmail 1.0.0 on Linux Mint 19.2 Tina 
Google chrome runs fine on the system. I can access all gmail accounts in Thunderbird, but I prefer a gmail-style interface. Cannot get this app to accept gmail accounts.

**Comment by geekgonecrazy** [comment]
See: #63
