### ISSUE TITLE
Error saying Browser or App may not be secure

### ISSUE THREAD

**Issue by BaaridunNasr** [openWMail/openWMail#79]
* Which version of openWMail are you using? [e.g. 1.3.1]
  Version 1.0.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
  Pop_OS 20.04

![Error](https://user-images.githubusercontent.com/12585952/81086186-cb881600-8f15-11ea-8a7b-ea011e5426d3.png)

Specifies that this browser or app may not be secure.

**Comment by Jackbaude** [comment]
Why was this closed? I still have this issue
