### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by JCKodel** [openWMail/openWMail#82]
* Which version of openWMail are you using? [e.g. 1.3.1]
Latest from snap

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OpenSuse Tumbleweed 20200813

```
 ~> sudo snap install openwmail
[sudo] password for root: 
Warning: /snap/bin was not found in your $PATH. If you've not restarted your session since you
         installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469 for more
         details.

openwmail 1.0.0 from Aaron (geekgonecrazy) installed

 ~> openwmail
No schema files found: doing nothing.
[1]    19288 illegal hardware instruction (core dumped)  openwmail
```

**Comment by geekgonecrazy** [comment]
I’ve gone ahead and actually unlisted the snap as for sure not supported any more.  Not sure what caused this.  Though guessing something between snapd and tumbleweed
