### ISSUE TITLE
arm64 builds

### ISSUE THREAD

**Issue by joske** [openWMail/openWMail#89]
* Which version of openWMail are you using? [e.g. 1.3.1]
none
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
asahi linux (linux on apple silicon macs) so ARM64 but of course same problem on raspberry pi

Please also provide builds on arm64, as the build process is complicated to manually build ourselves (need API key etc).

**Comment by WillPresley** [comment]
@joske Please see: https://github.com/openWMail/openWMail/issues/88#issuecomment-978047633
There are no (current) plans to get this project moving again, unless more maintainers come on board.
